services:
  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    hostname: nginx
  backend:
    image: skinet-backend
    container_name: backend
    build:
      context: /home/anakin-skywalker/Skinet/Skinet
      dockerfile: /home/anakin-skywalker/Skinet/Skinet/Dockerfile
        #ports:
        #- 5011:5011 #(host:container)
    stdin_open: true
    tty: true
    environment:
      ASPNETCORE_ENVIRONMENT: Production