version: '3.4'

services:

  backend:
    image: skinet-backend
    container_name: backend
    build:
      context: /home/anakin-skywalker/Skinet/Skinet
      dockerfile: /home/anakin-skywalker/Skinet/Skinet/Dockerfile
    stdin_open: true
    tty: true
    environment:
      ASPNETCORE_ENVIRONMENT: Production