name: skinet

run-name: skinet 🚀

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This is a job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: get sources
        uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/API

      - name: Build the Docker image
        working-directory: ${{ github.workspace }}/API
        run: docker build . -t altair961/API:latest
