name: Skinet

run-name: Skinet 🚀

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This is a job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: get sources
        uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/Skinet
  # This is a job called "deploy"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pull the image to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: | 
            docker-compose -f compose.yml down
#            docker container prune -f
#            docker image prune -f
#            docker volume prune -f
            ls
            git clone git@github.com:altair961/Skinet.git
            ls
            docker-compose -f compose.yml build --no-cache
            docker-compose -f compose.yml up